# Parallel Composition Demo

Basically, designing some tests.

## Prelims

In [1]:
import os, sys
import pandas as pd
import numpy as np
import sklearn
from sklearn.tree import (DecisionTreeClassifier,
                          DecisionTreeRegressor)
from sklearn.ensemble import (RandomForestClassifier,
                              RandomForestRegressor)

from os.path import dirname

/home/elia/Software/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [2]:
note_dir = os.getcwd()
root_dir = dirname(note_dir)
data_dir = os.path.join(root_dir, 'resc', 'data', 'tidy','nltcs')
src_dir = os.path.join(root_dir, "src")

sys.path.append(src_dir)

In [3]:
import morpheus

In [4]:
# Filter relevant stuff out
rel_fnames = [os.path.join(data_dir, f) for f in os.listdir(data_dir)
              if 'F00' in f
              if 'bayesfusion' not in f]

train_fn, test_fn = rel_fnames[0], rel_fnames[1]

# Get dfs
df_train, df_test = pd.read_csv(train_fn, header=None), pd.read_csv(test_fn, header=None)

# Get np.arrays
train, test = df_train.values, df_test.values

## Creating Dataset

In [5]:
def add_extra_column(a, nominal=True):
    assert isinstance(a, np.ndarray)
    n_rows, n_atts = a.shape
    
    if nominal:
        extra_col = np.random.randint(1,4, size=(n_rows, 1))
        extra_col.sort(axis=0)
    else:
        extra_col = np.random.rand(n_rows,1)
    
    
    return np.concatenate((a, extra_col), axis=1)

In [6]:
train, test = train[:,0:5], test[:, 0:5]

In [7]:
train, test = add_extra_column(train), add_extra_column(test)

In [8]:
train

array([[0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       ...,
       [0, 0, 0, 1, 1, 3],
       [0, 0, 0, 0, 0, 3],
       [0, 0, 1, 1, 1, 3]])

## Merging identical models

This really should not be an issue.

### Learning individual estimators

In [9]:
def learn_model(train, desc_ids, targ_ids, **kwargs):
    X, Y = train[:, desc_ids], train[:, targ_ids]
    
    if X.shape[1]==1: X = X.ravel()
    if Y.shape[1]==1: Y = Y.ravel()
    
    try:
        clf = RandomForestClassifier(**kwargs)
        clf.fit(X, Y)
    except ValueError:
        clf = RandomForestRegressor(**kwargs)
        clf.fit(X, Y)
    
    clf.desc_ids = desc_ids
    clf.targ_ids = targ_ids
    return clf

In [10]:
n_rows, n_atts = train.shape
print(n_rows, n_atts)

19416 6


In [11]:
atts_ids = list(range(n_atts))
atts_ids

[0, 1, 2, 3, 4, 5]

We assume the last n attributes to be the targets.

In [12]:
n_targs = 1
desc_ids = atts_ids[:-n_targs]
targ_ids = atts_ids[-n_targs:]

In [13]:
m_list = []
for m_idx in range(2):
    m = learn_model(train, desc_ids, targ_ids)
    m.desc_ids = desc_ids
    m.targ_ids = targ_ids
    m_list.append(m)

### Composing estimators

In [14]:
pc = morpheus.ParallelComposition()

for m in m_list:
    pc.add_estimator(m)

In [15]:
pc.desc_ids, pc.targ_ids

(array([0., 1., 2., 3., 4.]), array([5.]))

In [16]:
pc.classes_

[array([1., 2., 3.])]

In [17]:
m_list[0].classes_, m_list[1].classes_

(array([1, 2, 3]), array([1, 2, 3]))

### Predictions

In [18]:
pc.targ_weights

array([2.])

In [19]:
pc.targ_types 

['nominal']

In [20]:
pc.predict_proba(test[:, desc_ids])

array([[0.33970392, 0.33654715, 0.32374893],
       [0.3301444 , 0.32984697, 0.34000864],
       [0.3216116 , 0.34535353, 0.33303487],
       ...,
       [0.33970392, 0.33654715, 0.32374893],
       [0.33970392, 0.33654715, 0.32374893],
       [0.3216116 , 0.34535353, 0.33303487]])

## Merging slightly different models.

### Challenge one: different targets.

In [21]:
targ_ids_1 = [5]
desc_ids_1 = [0,1,2,3]

targ_ids_2 = [4]
desc_ids_2 = [0,1,2,3]

all_desc_ids = [desc_ids_1, desc_ids_2]
all_targ_ids = [targ_ids_1, targ_ids_2]



In [22]:
atts_ids

[0, 1, 2, 3, 4, 5]

In [23]:
m_list = []
ids = zip(all_desc_ids, all_targ_ids)
for desc_ids, targ_ids in ids:
    print(desc_ids, targ_ids)
    m = learn_model(train, desc_ids, targ_ids)
    m.desc_ids = desc_ids
    m.targ_ids = targ_ids
    m_list.append(m)

[0, 1, 2, 3] [5]
[0, 1, 2, 3] [4]


In [24]:
pc2 = morpheus.ParallelComposition()

for m in m_list:
    pc2.add_estimator(m)

In [25]:
pc2.add_estimator(m_list[0])

In [26]:
pc2.pretty_print()


        # Main
        Descriptive attributes:     [0. 1. 2. 3.]
        Target attributes:          [4. 5.]
        
        ## On types (mostly nominals)
        Target attribute types:                     ['nominal', 'nominal']
        N_classes of nominal target attributes:     [2, 3]
        Classes of nominal target attributes:       [array([0., 1.]), array([1., 2., 3.])]
        
        ## Weights
        Total weights of target attributes:         [1. 2.]
        


In [27]:
pc2.predict_proba(test[:, desc_ids_1])

[array([[0.68122108, 0.31877892],
        [0.25704563, 0.74295437],
        [0.68122108, 0.31877892],
        ...,
        [0.68122108, 0.31877892],
        [0.68122108, 0.31877892],
        [0.68122108, 0.31877892]]),
 array([[0.33235983, 0.34173074, 0.32590943],
        [0.33077098, 0.33097445, 0.33825456],
        [0.33235983, 0.34173074, 0.32590943],
        ...,
        [0.33235983, 0.34173074, 0.32590943],
        [0.33235983, 0.34173074, 0.32590943],
        [0.33235983, 0.34173074, 0.32590943]])]

### Challenge two: (Partly overlapping targets)

In [28]:
targ_ids_1 = [4,5]
desc_ids_1 = [0,1,2]

targ_ids_2 = [3,4]
desc_ids_2 = [0,1,2]

all_desc_ids = [desc_ids_1, desc_ids_2]
all_targ_ids = [targ_ids_1, targ_ids_2]

In [29]:
ids = zip(all_desc_ids, all_targ_ids) # Make iterator here.
m_list = []

for desc_ids, targ_ids in ids:
    print(desc_ids, targ_ids)
    m = learn_model(train, desc_ids, targ_ids)
    m.desc_ids = desc_ids
    m.targ_ids = targ_ids
    m_list.append(m)

[0, 1, 2] [4, 5]
[0, 1, 2] [3, 4]


In [30]:
pc2 = morpheus.ParallelComposition()

for m in m_list:
    pc2.add_estimator(m)

In [31]:
pc2.pretty_print()


        # Main
        Descriptive attributes:     [0. 1. 2.]
        Target attributes:          [3. 4. 5.]
        
        ## On types (mostly nominals)
        Target attribute types:                     ['nominal', 'nominal', 'nominal']
        N_classes of nominal target attributes:     [2, 2, 3]
        Classes of nominal target attributes:       [array([0., 1.]), array([0., 1.]), array([1., 2., 3.])]
        
        ## Weights
        Total weights of target attributes:         [1. 2. 1.]
        


In [32]:
pc2.predict_proba(test[:, desc_ids_1])

[array([[0.64475, 0.35525],
        [0.64475, 0.35525],
        [0.64475, 0.35525],
        ...,
        [0.64475, 0.35525],
        [0.64475, 0.35525],
        [0.64475, 0.35525]]), array([[0.5322339, 0.4677661],
        [0.5322339, 0.4677661],
        [0.5322339, 0.4677661],
        ...,
        [0.5322339, 0.4677661],
        [0.5322339, 0.4677661],
        [0.5322339, 0.4677661]]), array([[0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523],
        ...,
        [0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523]])]

In [33]:
# Add dumbass model => Changes predictions.
m = learn_model(train[1:10,:], desc_ids_2, targ_ids_2)
m.desc_ids = desc_ids_2
m.targ_ids = targ_ids_2

In [34]:
pc2.add_estimator(m)

In [35]:
pc2.pretty_print()


        # Main
        Descriptive attributes:     [0. 1. 2.]
        Target attributes:          [3. 4. 5.]
        
        ## On types (mostly nominals)
        Target attribute types:                     ['nominal', 'nominal', 'nominal']
        N_classes of nominal target attributes:     [2, 2, 3]
        Classes of nominal target attributes:       [array([0., 1.]), array([0., 1.]), array([1., 2., 3.])]
        
        ## Weights
        Total weights of target attributes:         [2. 3. 1.]
        


In [36]:
pc2.predict_proba(test[:, desc_ids_1])

[array([[0.63019246, 0.36980754],
        [0.63019246, 0.36980754],
        [0.63019246, 0.36980754],
        ...,
        [0.63019246, 0.36980754],
        [0.63019246, 0.36980754],
        [0.63019246, 0.36980754]]), array([[0.51236229, 0.48763771],
        [0.51236229, 0.48763771],
        [0.51236229, 0.48763771],
        ...,
        [0.51236229, 0.48763771],
        [0.51236229, 0.48763771],
        [0.51236229, 0.48763771]]), array([[0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523],
        ...,
        [0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523],
        [0.33396864, 0.33804613, 0.32798523]])]

## Adding regressors to the mix

### Adding numerical target

In [37]:
train, test = add_extra_column(train, nominal=False), add_extra_column(test, nominal=False)
train, test = add_extra_column(train, nominal=False), add_extra_column(test, nominal=False)

In [38]:
pd.DataFrame(train).head() # Useful for inspection.

0    1    2    3    4    5         6         7
0  0.0  0.0  0.0  0.0  0.0  1.0  0.044932  0.112953
1  1.0  0.0  1.0  1.0  1.0  1.0  0.749327  0.153926
2  1.0  1.0  1.0  1.0  1.0  1.0  0.631005  0.163216
3  0.0  0.0  0.0  0.0  0.0  1.0  0.538603  0.981877
4  0.0  0.0  0.0  0.0  1.0  1.0  0.512004  0.581816

In [39]:
targ_ids_1 = [6]
desc_ids_1 = [0,1,2,3]

targ_ids_2 = [4,5]
desc_ids_2 = [0,1,2,3]

targ_ids_3 = [6,7]
desc_ids_3 = [0,1,2,3]

all_desc_ids = [desc_ids_1, desc_ids_2, desc_ids_3]
all_targ_ids = [targ_ids_1, targ_ids_2, targ_ids_3]

In [40]:
m_list = []
ids = zip(all_desc_ids, all_targ_ids)
for desc_ids, targ_ids in ids:
    print(desc_ids, targ_ids)
    m = learn_model(train, desc_ids, targ_ids)
    m.desc_ids = desc_ids
    m.targ_ids = targ_ids
    m_list.append(m)

[0, 1, 2, 3] [6]
[0, 1, 2, 3] [4, 5]
[0, 1, 2, 3] [6, 7]


### Composing estimators

In [41]:
pc3 = morpheus.ParallelComposition()

for m in m_list:
    pc3.add_estimator(m)

In [42]:
pc3.pretty_print()


        # Main
        Descriptive attributes:     [0. 1. 2. 3.]
        Target attributes:          [4. 5. 6. 7.]
        
        ## On types (mostly nominals)
        Target attribute types:                     ['nominal', 'nominal', 'numeric', 'numeric']
        N_classes of nominal target attributes:     [2, 3]
        Classes of nominal target attributes:       [array([0., 1.]), array([1., 2., 3.])]
        
        ## Weights
        Total weights of target attributes:         [1. 1. 2. 1.]
        


In [43]:
pc3.predict_proba(test[:, desc_ids_1])

[array([[0.6807192 , 0.3192808 ],
        [0.25986775, 0.74013225],
        [0.6807192 , 0.3192808 ],
        ...,
        [0.6807192 , 0.3192808 ],
        [0.6807192 , 0.3192808 ],
        [0.6807192 , 0.3192808 ]]),
 array([[0.33273609, 0.34165639, 0.32560752],
        [0.3363966 , 0.33016843, 0.33343497],
        [0.33273609, 0.34165639, 0.32560752],
        ...,
        [0.33273609, 0.34165639, 0.32560752],
        [0.33273609, 0.34165639, 0.32560752],
        [0.33273609, 0.34165639, 0.32560752]])]

In [44]:
pc3.predict_numeric(test[:, desc_ids_1])

array([[0.49582658, 0.50073332],
       [0.49652513, 0.49709948],
       [0.49582658, 0.50073332],
       ...,
       [0.49582658, 0.50073332],
       [0.49582658, 0.50073332],
       [0.49582658, 0.50073332]])

In [46]:
pc3.predict(test[:, desc_ids_1])

array([[0.        , 2.        , 0.49582658, 0.50073332],
       [1.        , 1.        , 0.49652513, 0.49709948],
       [0.        , 2.        , 0.49582658, 0.50073332],
       ...,
       [0.        , 2.        , 0.49582658, 0.50073332],
       [0.        , 2.        , 0.49582658, 0.50073332],
       [0.        , 2.        , 0.49582658, 0.50073332]])

In [47]:
pc3.targ_ids

array([4., 5., 6., 7.])